import type {Theme, ThemePreset} from '@/types/ui';

export const themes: Record<ThemePreset, Theme> = {
	'tokyo-night': {
		name: 'tokyo-night',
		displayName: 'Tokyo Night',
		themeType: 'dark',
		colors: {
			text: '#c0caf5',
			base: '#1a1b26',
			primary: '#bb9af7',
			tool: '#7dcfff',
			success: '#7AF778',
			error: '#f7768e',
			secondary: '#565f89',
			info: '#2ac3de',
			warning: '#e0af68',
			diffAdded: '#1e2f1e',
			diffRemoved: '#2f1e1e',
			diffAddedText: '#9ece6a',
			diffRemovedText: '#f7768e',
		},
	},
	'synthwave-84': {
		name: 'synthwave-84',
		displayName: "Synthwave '84",
		themeType: 'dark',
		colors: {
			text: '#f8f8f2',
			base: '#2b213a',
			primary: '#ff006a',
			tool: '#00d9ff',
			success: '#a6e22e',
			error: '#ff3838',
			secondary: '#8a7ca8',
			info: '#66d9ef',
			warning: '#ffb86c',
			diffAdded: '#2d4a1e',
			diffRemoved: '#4a1e2d',
			diffAddedText: '#a6e22e',
			diffRemovedText: '#ff3838',
		},
	},
	'forest-night': {
		name: 'forest-night',
		displayName: 'Forest Night',
		themeType: 'dark',
		colors: {
			text: '#d3c6aa',
			base: '#2d353b',
			primary: '#a7c080',
			tool: '#83c092',
			success: '#a7c080',
			error: '#e67e80',
			secondary: '#859289',
			info: '#7fbbb3',
			warning: '#dbbc7f',
			diffAdded: '#2d3f2d',
			diffRemoved: '#3f2d2d',
			diffAddedText: '#a7c080',
			diffRemovedText: '#e67e80',
		},
	},
	'material-ocean': {
		name: 'material-ocean',
		displayName: 'Material Ocean',
		themeType: 'dark',
		colors: {
			text: '#b3e5fc',
			base: '#0d1117',
			primary: '#26c6da',
			tool: '#4fc3f7',
			success: '#66bb6a',
			error: '#ef5350',
			secondary: '#78909c',
			info: '#29b6f6',
			warning: '#ffa726',
			diffAdded: '#1a3d2e',
			diffRemoved: '#3d1a1a',
			diffAddedText: '#66bb6a',
			diffRemovedText: '#ef5350',
		},
	},
	'sunset-glow': {
		name: 'sunset-glow',
		displayName: 'Sunset Glow',
		themeType: 'dark',
		colors: {
			text: '#fdf4dc',
			base: '#2d1b14',
			primary: '#ff6b35',
			tool: '#f7941d',
			success: '#52c41a',
			error: '#ff4757',
			secondary: '#a0826d',
			info: '#ffa726',
			warning: '#ffca28',
			diffAdded: '#2d4a1e',
			diffRemoved: '#4a1e2d',
			diffAddedText: '#52c41a',
			diffRemovedText: '#ff4757',
		},
	},
	'nord-frost': {
		name: 'nord-frost',
		displayName: 'Nord Frost',
		themeType: 'dark',
		colors: {
			text: '#eceff4',
			base: '#2e3440',
			primary: '#88c0d0',
			tool: '#8fbcbb',
			success: '#a3be8c',
			error: '#bf616a',
			secondary: '#4c566a',
			info: '#5e81ac',
			warning: '#ebcb8b',
			diffAdded: '#2d3f2d',
			diffRemoved: '#3f2d2d',
			diffAddedText: '#a3be8c',
			diffRemovedText: '#bf616a',
		},
	},
	'rose-pine-dawn': {
		name: 'rose-pine-dawn',
		displayName: 'Rosé Pine Dawn',
		themeType: 'light',
		colors: {
			text: '#575279',
			base: '#faf4ed',
			primary: '#907aa9',
			tool: '#56949f',
			success: '#618a3d',
			error: '#b4637a',
			secondary: '#9893a5',
			info: '#286983',
			warning: '#ea9d34',
			diffAdded: '#f0f0e8',
			diffRemoved: '#f2e9e1',
			diffAddedText: '#618a3d',
			diffRemovedText: '#b4637a',
		},
	},
	'neon-jungle': {
		name: 'neon-jungle',
		displayName: 'Neon Jungle',
		themeType: 'dark',
		colors: {
			text: '#e0ffe0',
			base: '#0d1f0d',
			primary: '#39ff14',
			tool: '#00ff7f',
			success: '#32cd32',
			error: '#ff1493',
			secondary: '#4a7c59',
			info: '#00ffff',
			warning: '#ffff00',
			diffAdded: '#1a4d1a',
			diffRemoved: '#4d1a4d',
			diffAddedText: '#32cd32',
			diffRemovedText: '#ff1493',
		},
	},
	'midnight-amethyst': {
		name: 'midnight-amethyst',
		displayName: 'Midnight Amethyst',
		themeType: 'dark',
		colors: {
			text: '#e6e6fa',
			base: '#0f0a1a',
			primary: '#9966cc',
			tool: '#ba55d3',
			success: '#9370db',
			error: '#dc143c',
			secondary: '#6a5acd',
			info: '#c0c0c0',
			warning: '#dda0dd',
			diffAdded: '#2d1a4d',
			diffRemoved: '#4d1a1a',
			diffAddedText: '#9370db',
			diffRemovedText: '#dc143c',
		},
	},
	'desert-mirage': {
		name: 'desert-mirage',
		displayName: 'Desert Mirage',
		themeType: 'dark',
		colors: {
			text: '#fff8dc',
			base: '#2f1b14',
			primary: '#ffd700',
			tool: '#daa520',
			success: '#228b22',
			error: '#dc143c',
			secondary: '#d2691e',
			info: '#40e0d0',
			warning: '#ffa500',
			diffAdded: '#2d4a1e',
			diffRemoved: '#4a1e1e',
			diffAddedText: '#228b22',
			diffRemovedText: '#dc143c',
		},
	},
	'cherry-blossom': {
		name: 'cherry-blossom',
		displayName: 'Cherry Blossom',
		themeType: 'light',
		colors: {
			text: '#5a5a5a',
			base: '#fef7f0',
			primary: '#ffb6c1',
			tool: '#20b2aa',
			success: '#3cb371',
			error: '#cd5c5c',
			secondary: '#bc8f8f',
			info: '#4682b4',
			warning: '#f4a460',
			diffAdded: '#f0fff0',
			diffRemoved: '#ffe4e1',
			diffAddedText: '#3cb371',
			diffRemovedText: '#cd5c5c',
		},
	},
	'electric-storm': {
		name: 'electric-storm',
		displayName: 'Electric Storm',
		themeType: 'dark',
		colors: {
			text: '#f0f0f0',
			base: '#1c1c1c',
			primary: '#ffff00',
			tool: '#00bfff',
			success: '#adff2f',
			error: '#ff4500',
			secondary: '#696969',
			info: '#87ceeb',
			warning: '#ffd700',
			diffAdded: '#2d4a1e',
			diffRemoved: '#4a1e1e',
			diffAddedText: '#adff2f',
			diffRemovedText: '#ff4500',
		},
	},
	'deep-sea': {
		name: 'deep-sea',
		displayName: 'Deep Sea',
		themeType: 'dark',
		colors: {
			text: '#b0e0e6',
			base: '#000080',
			primary: '#008b8b',
			tool: '#00ced1',
			success: '#20b2aa',
			error: '#ff6347',
			secondary: '#4682b4',
			info: '#40e0d0',
			warning: '#ffa500',
			diffAdded: '#1e3a3a',
			diffRemoved: '#3a1e1e',
			diffAddedText: '#20b2aa',
			diffRemovedText: '#ff6347',
		},
	},
	'volcanic-ash': {
		name: 'volcanic-ash',
		displayName: 'Volcanic Ash',
		themeType: 'dark',
		colors: {
			text: '#dcdcdc',
			base: '#2f2f2f',
			primary: '#dc143c',
			tool: '#ff4500',
			success: '#32cd32',
			error: '#ff0000',
			secondary: '#708090',
			info: '#ffa500',
			warning: '#ffff00',
			diffAdded: '#2d4a1e',
			diffRemoved: '#4a1e1e',
			diffAddedText: '#32cd32',
			diffRemovedText: '#ff0000',
		},
	},
	'cyberpunk-mint': {
		name: 'cyberpunk-mint',
		displayName: 'Cyberpunk Mint',
		themeType: 'dark',
		colors: {
			text: '#f0fff0',
			base: '#000000',
			primary: '#00ff7f',
			tool: '#98fb98',
			success: '#32cd32',
			error: '#ff00ff',
			secondary: '#2e8b57',
			info: '#40e0d0',
			warning: '#ffff00',
			diffAdded: '#1a4d1a',
			diffRemoved: '#4d1a4d',
			diffAddedText: '#32cd32',
			diffRemovedText: '#ff00ff',
		},
	},
	dracula: {
		name: 'dracula',
		displayName: 'Dracula',
		themeType: 'dark',
		colors: {
			text: '#f8f8f2',
			base: '#282a36',
			primary: '#ff79c6',
			tool: '#8be9fd',
			success: '#50fa7b',
			error: '#ff5555',
			secondary: '#bd93f9',
			info: '#f1fa8c',
			warning: '#ffb86c',
			diffAdded: '#2d4a2d',
			diffRemoved: '#4a2d2d',
			diffAddedText: '#50fa7b',
			diffRemovedText: '#ff5555',
		},
	},
	'catppuccin-latte': {
		name: 'catppuccin-latte',
		displayName: 'Catppuccin Latte',
		themeType: 'light',
		colors: {
			text: '#4c4f69',
			base: '#eff1f5',
			primary: '#8839ef',
			tool: '#1e66f5',
			secondary: '#5c5f77',
			success: '#40a02b',
			error: '#d20f39',
			info: '#209fb5',
			warning: '#df8e1d',
			diffAdded: '#40a02b',
			diffRemoved: '#d20f39',
			diffAddedText: '#40a02b',
			diffRemovedText: '#d20f39',
			gradientColors: ['#dc8a78', '#8839ef', '#1e66f5'],
		},
	},
	'catppuccin-frappe': {
		name: 'catppuccin-frappe',
		displayName: 'Catppuccin Frappé',
		themeType: 'dark',
		colors: {
			text: '#c6d0f5',
			base: '#303446',
			primary: '#ca9ee6',
			tool: '#8caaee',
			secondary: '#b5bfe2',
			success: '#a6d189',
			error: '#e78284',
			info: '#85c1dc',
			warning: '#e5c890',
			diffAdded: '#a6d189',
			diffRemoved: '#e78284',
			diffAddedText: '#a6d189',
			diffRemovedText: '#e78284',
			gradientColors: ['#f2d5cf', '#ca9ee6', '#8caaee'],
		},
	},
	'catppuccin-macchiato': {
		name: 'catppuccin-macchiato',
		displayName: 'Catppuccin Macchiato',
		themeType: 'dark',
		colors: {
			text: '#cad3f5',
			base: '#24273a',
			primary: '#c6a0f6',
			tool: '#8aadf4',
			secondary: '#b8c0e0',
			success: '#a6da95',
			error: '#ed8796',
			info: '#7dc4e4',
			warning: '#eed49f',
			diffAdded: '#a6da95',
			diffRemoved: '#ed8796',
			diffAddedText: '#a6da95',
			diffRemovedText: '#ed8796',
			gradientColors: ['#f4dbd6', '#c6a0f6', '#8aadf4'],
		},
	},
	'catppuccin-mocha': {
		name: 'catppuccin-mocha',
		displayName: 'Catppuccin Mocha',
		themeType: 'dark',
		colors: {
			text: '#cdd6f4',
			base: '#1e1e2e',
			primary: '#cba6f7',
			tool: '#89b4fa',
			secondary: '#bac2de',
			success: '#a6e3a1',
			error: '#f38ba8',
			info: '#74c7ec',
			warning: '#f9e2af',
			diffAdded: '#a6e3a1',
			diffRemoved: '#f38ba8',
			diffAddedText: '#a6e3a1',
			diffRemovedText: '#f38ba8',
			gradientColors: ['#f5e0dc', '#cba6f7', '#89b4fa'],
		},
	},
};

export function getThemeColors(themePreset: ThemePreset) {
	return themes[themePreset].colors;
}

export const defaultTheme: ThemePreset = 'tokyo-night';
