packages:
  - .
  - plugins/*

ignoredBuiltDependencies:
  - protobufjs

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
